baseurl = "/"
languageCode = "en-us"
title = "Tasty Licks"

[params]
  description = "[@_thomasphillips](https://github.com/thomasphillips3/hugo-restaurant-tutorial) Learning to use [Netlify](https://www.netlify.com/docs/) and [Hugo](https://github.com/netlify/victor-hugo)."

[[menu.main]]
    name = "Food"
    url  = "/food"
    weight = 1
[[menu.main]]
    name = "Drinks"
    url = "/drinks"
    weight = 2
[[menu.main]]
    name = "Gallery"
    url = "/gallery"
    weight = 3
[[menu.main]]
    name = "Make a Reservation"
    url = "/contact"
    weight = 4
[[menu.main]]
    name = "About"
    url  = "/about"
    weight = 999
